//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResXManager.View.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResourceFilter {
            get {
                return ((string)(this["ResourceFilter"]));
            }
            set {
                this["ResourceFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en=en-US")]
        public string NeutralCultureCountyOverrides {
            get {
                return ((string)(this["NeutralCultureCountyOverrides"]));
            }
            set {
                this["NeutralCultureCountyOverrides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string VisibleCommentColumns {
            get {
                return ((string)(this["VisibleCommentColumns"]));
            }
            set {
                this["VisibleCommentColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HiddenLanguageColumns {
            get {
                return ((string)(this["HiddenLanguageColumns"]));
            }
            set {
                this["HiddenLanguageColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsIndexColumnVisible {
            get {
                return ((bool)(this["IsIndexColumnVisible"]));
            }
            set {
                this["IsIndexColumnVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCellSelectionEnabled {
            get {
                return ((bool)(this["IsCellSelectionEnabled"]));
            }
            set {
                this["IsCellSelectionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AreAllFilesSelected {
            get {
                return ((bool)(this["AreAllFilesSelected"]));
            }
            set {
                this["AreAllFilesSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsWrapLinesEnabled {
            get {
                return ((bool)(this["IsWrapLinesEnabled"]));
            }
            set {
                this["IsWrapLinesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsOpenSourceMessageConfirmed {
            get {
                return ((bool)(this["IsOpenSourceMessageConfirmed"]));
            }
            set {
                this["IsOpenSourceMessageConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFindCodeReferencesEnabled {
            get {
                return ((bool)(this["IsFindCodeReferencesEnabled"]));
            }
            set {
                this["IsFindCodeReferencesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranslationUnselectedTargetCultures {
            get {
                return ((string)(this["TranslationUnselectedTargetCultures"]));
            }
            set {
                this["TranslationUnselectedTargetCultures"] = value;
            }
        }
    }
}
