//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tomenglertde.ResXManager.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tomenglertde.ResXManager.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string AddNewItemTemplate {
            get {
                return ResourceManager.GetString("AddNewItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty..
        /// </summary>
        internal static string ClipboardIsEmpty {
            get {
                return ResourceManager.GetString("ClipboardIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate keys in &apos;{0}&apos;:
        ///{1}
        ///.
        /// </summary>
        internal static string DuplicateKeyError {
            get {
                return ResourceManager.GetString("DuplicateKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file &apos;{0}&apos;:
        ///{1}
        ///.
        /// </summary>
        internal static string FileSaveError {
            get {
                return ResourceManager.GetString("FileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least three columns expected..
        /// </summary>
        internal static string ImportColumnMismatchError {
            get {
                return ResourceManager.GetString("ImportColumnMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate language in header..
        /// </summary>
        internal static string ImportDuplicateLanguageError {
            get {
                return ResourceManager.GetString("ImportDuplicateLanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed. Nothing has been imported!.
        /// </summary>
        internal static string ImportFailedError {
            get {
                return ResourceManager.GetString("ImportFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed partially. Some columns have been already imported, but not all!.
        /// </summary>
        internal static string ImportFailedPartiallyError {
            get {
                return ResourceManager.GetString("ImportFailedPartiallyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard header expected..
        /// </summary>
        internal static string ImportHeaderMismatchError {
            get {
                return ResourceManager.GetString("ImportHeaderMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent usage of double quote..
        /// </summary>
        internal static string ImportInconsistentDoubleQuoteError {
            get {
                return ResourceManager.GetString("ImportInconsistentDoubleQuoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A normalized table is expected..
        /// </summary>
        internal static string ImportNormalizedTableExpected {
            get {
                return ResourceManager.GetString("ImportNormalizedTableExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse empty text..
        /// </summary>
        internal static string ImportParseEmptyTextError {
            get {
                return ResourceManager.GetString("ImportParseEmptyTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid RESX resource file: No xml root..
        /// </summary>
        internal static string InvalidResourceFileError {
            get {
                return ResourceManager.GetString("InvalidResourceFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid RESX resource file: Not all entries have a name attribute..
        /// </summary>
        internal static string InvalidResourceFileNameAttributeMissingError {
            get {
                return ResourceManager.GetString("InvalidResourceFileNameAttributeMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid RESX resource file: Not all entries have a value attribute..
        /// </summary>
        internal static string InvalidResourceFileValueAttributeMissingError {
            get {
                return ResourceManager.GetString("InvalidResourceFileValueAttributeMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is not defined: {0}.
        /// </summary>
        internal static string LanguageNotDefinedError {
            get {
                return ResourceManager.GetString("LanguageNotDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResX Resource Manager.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
