//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

namespace tomenglertde.ResXManager.Model.Properties {
    using System;

    using JetBrains.Annotations;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by a text template.
    // To add or remove a member, edit your .ResX file.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tomenglertde.ResXManager.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate keys in '{0}':&amp;#13;&amp;#10;{1}&amp;....
        /// </summary>
        [NotNull]
        public static string DuplicateKeyError {
            get {
                return ResourceManager.GetString("DuplicateKeyError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show an error message and don't load the resource.
        /// </summary>
        [NotNull]
        public static string DuplicateKeyHandling_Fail {
            get {
                return ResourceManager.GetString("DuplicateKeyHandling_Fail", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postfix duplicate/empty keys with "_Duplicate[#]"/....
        /// </summary>
        [NotNull]
        public static string DuplicateKeyHandling_Rename {
            get {
                return ResourceManager.GetString("DuplicateKeyHandling_Rename", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty keys in '{0}'.
        /// </summary>
        [NotNull]
        public static string EmptyKeysError {
            get {
                return ResourceManager.GetString("EmptyKeysError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;?xml version="1.0" encoding="utf-8"?&amp;g....
        /// </summary>
        [NotNull]
        public static string EmptyResxTemplate {
            get {
                return ResourceManager.GetString("EmptyResxTemplate", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple sheets.
        /// </summary>
        [NotNull]
        public static string ExcelExport_MultipleSheets {
            get {
                return ResourceManager.GetString("ExcelExport_MultipleSheets", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plain text, tab delimited.
        /// </summary>
        [NotNull]
        public static string ExcelExport_PlainTextTabDelimited {
            get {
                return ResourceManager.GetString("ExcelExport_PlainTextTabDelimited", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single sheet.
        /// </summary>
        [NotNull]
        public static string ExcelExport_SingleSheet {
            get {
                return ResourceManager.GetString("ExcelExport_SingleSheet", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error saving file '{0}':&amp;#13;&amp;#10;{1}&amp;....
        /// </summary>
        [NotNull]
        public static string FileSaveError {
            get {
                return ResourceManager.GetString("FileSaveError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least three columns expected..
        /// </summary>
        [NotNull]
        public static string ImportColumnMismatchError {
            get {
                return ResourceManager.GetString("ImportColumnMismatchError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate language in header..
        /// </summary>
        [NotNull]
        public static string ImportDuplicateLanguageError {
            get {
                return ResourceManager.GetString("ImportDuplicateLanguageError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed. Nothing has been imported!.
        /// </summary>
        [NotNull]
        public static string ImportFailedError {
            get {
                return ResourceManager.GetString("ImportFailedError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed partially. Some columns have been al....
        /// </summary>
        [NotNull]
        public static string ImportFailedPartiallyError {
            get {
                return ResourceManager.GetString("ImportFailedPartiallyError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standard header expected..
        /// </summary>
        [NotNull]
        public static string ImportHeaderMismatchError {
            get {
                return ResourceManager.GetString("ImportHeaderMismatchError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The language "{0}" can't be edited. The operation ....
        /// </summary>
        [NotNull]
        public static string ImportLanguageNotEditable {
            get {
                return ResourceManager.GetString("ImportLanguageNotEditable", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The sheet "{0}" can't be imported; there is no mat....
        /// </summary>
        [NotNull]
        public static string ImportMapSheetError {
            get {
                return ResourceManager.GetString("ImportMapSheetError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid RESX resource file: No xml root....
        /// </summary>
        [NotNull]
        public static string InvalidResourceFileError {
            get {
                return ResourceManager.GetString("InvalidResourceFileError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid RESX resource file: Not all ent....
        /// </summary>
        [NotNull]
        public static string InvalidResourceFileNameAttributeMissingError {
            get {
                return ResourceManager.GetString("InvalidResourceFileNameAttributeMissingError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid RESX resource file: Not all ent....
        /// </summary>
        [NotNull]
        public static string InvalidResourceFileValueAttributeMissingError {
            get {
                return ResourceManager.GetString("InvalidResourceFileValueAttributeMissingError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This key already exists: {0}.
        /// </summary>
        [NotNull]
        public static string KeyAlreadyExists {
            get {
                return ResourceManager.GetString("KeyAlreadyExists", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language is not defined: "{0}".
        /// </summary>
        [NotNull]
        public static string LanguageNotDefinedError {
            get {
                return ResourceManager.GetString("LanguageNotDefinedError", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        [NotNull]
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not all resource files are editable.
        /// </summary>
        [NotNull]
        public static string NotAllLanguagesAreEditable {
            get {
                return ResourceManager.GetString("NotAllLanguagesAreEditable", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item is invariant but contains a value.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntry_Error_InvariantWithValue {
            get {
                return ResourceManager.GetString("ResourceTableEntry_Error_InvariantWithValue", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing translation.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntry_Error_MissingTranslation {
            get {
                return ResourceManager.GetString("ResourceTableEntry_Error_MissingTranslation", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning: This item contains string format paramete....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntry_Error_StringFormatParameterMismatch {
            get {
                return ResourceManager.GetString("ResourceTableEntry_Error_StringFormatParameterMismatch", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This rule verifies that the punctuation of the ent....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationLead_Description {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationLead_Description", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The punctuation at the start of the messages doesn....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationLead_Error_Intro {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationLead_Error_Intro", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No punctuation was expected at the start of the me....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationLead_Error_NoPunctuationExpected {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationLead_Error_NoPunctuationExpected", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The expected leading punctuation sequence is: {0}.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationLead_Error_PunctuationSeqExpected {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationLead_Error_PunctuationSeqExpected", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Leading punctuation.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationLead_Name {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationLead_Name", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This rule verifies the punctuation at the end of t....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationTail_Description {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationTail_Description", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The punctuation at the end of the messages doesn't....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationTail_Error_Intro {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationTail_Error_Intro", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No punctuation was expected at the end of the mess....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationTail_Error_NoPunctuationExpected {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationTail_Error_NoPunctuationExpected", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The expected trailing punctuation sequence is: {0}.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationTail_Error_PunctuationSeqExpected {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationTail_Error_PunctuationSeqExpected", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trailing punctuation.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRulePunctuationTail_Name {
            get {
                return ResourceManager.GetString("ResourceTableEntryRulePunctuationTail_Name", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This rule verifies that the string format paramete....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleStringFormat_Description {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleStringFormat_Description", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Matching string format parameters.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleStringFormat_Name {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleStringFormat_Name", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This rule verifies that the whitespaces at the sta....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceLead_Description {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceLead_Description", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The whitespaces at the start of the sequence don't....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceLead_Error_Intro {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceLead_Error_Intro", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No whitespaces are expected at the start of the se....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceLead_Error_NoWhiteSpaceExpected {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceLead_Error_NoWhiteSpaceExpected", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The expected whitespace sequence is: {0}.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceLead_Error_WhiteSpaceSeqExpected {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceLead_Error_WhiteSpaceSeqExpected", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Leading whitespace.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceLead_Name {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceLead_Name", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This rule verifies that the trailing whitespaces o....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceTail_Description {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceTail_Description", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The whitespaces at the end of the sequence don't m....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceTail_Error_Intro {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceTail_Error_Intro", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No whitespaces are expected at the end of the sequ....
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceTail_Error_NoWhiteSpaceExpected {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceTail_Error_NoWhiteSpaceExpected", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The expected whitespace sequence is: {0}.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceTail_Error_WhiteSpaceSeqExpected {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceTail_Error_WhiteSpaceSeqExpected", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trailing whitespace.
        /// </summary>
        [NotNull]
        public static string ResourceTableEntryRuleWhiteSpaceTail_Name {
            get {
                return ResourceManager.GetString("ResourceTableEntryRuleWhiteSpaceTail_Name", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Snapshot: "{0}".
        /// </summary>
        [NotNull]
        public static string SnapshotAnnotation {
            get {
                return ResourceManager.GetString("SnapshotAnnotation", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ResX Resource Manager.
        /// </summary>
        /// <remarks>
        /// @Invariant
        /// </remarks>
        [NotNull]
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture) ?? string.Empty;
            }
        }
    }

    /// <summary>
    /// Keys of all available strings in the applications resx-resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public enum StringResourceKey
    {
        /// <summary>
        ///   Looks up a localized string similar to Duplicate keys in '{0}':&amp;#13;&amp;#10;{1}&amp;....
        /// </summary>
        DuplicateKeyError,
        /// <summary>
        ///   Looks up a localized string similar to Show an error message and don't load the resource.
        /// </summary>
        DuplicateKeyHandling_Fail,
        /// <summary>
        ///   Looks up a localized string similar to Postfix duplicate/empty keys with "_Duplicate[#]"/....
        /// </summary>
        DuplicateKeyHandling_Rename,
        /// <summary>
        ///   Looks up a localized string similar to Empty keys in '{0}'.
        /// </summary>
        EmptyKeysError,
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;?xml version="1.0" encoding="utf-8"?&amp;g....
        /// </summary>
        EmptyResxTemplate,
        /// <summary>
        ///   Looks up a localized string similar to Multiple sheets.
        /// </summary>
        ExcelExport_MultipleSheets,
        /// <summary>
        ///   Looks up a localized string similar to Plain text, tab delimited.
        /// </summary>
        ExcelExport_PlainTextTabDelimited,
        /// <summary>
        ///   Looks up a localized string similar to Single sheet.
        /// </summary>
        ExcelExport_SingleSheet,
        /// <summary>
        ///   Looks up a localized string similar to Error saving file '{0}':&amp;#13;&amp;#10;{1}&amp;....
        /// </summary>
        FileSaveError,
        /// <summary>
        ///   Looks up a localized string similar to At least three columns expected..
        /// </summary>
        ImportColumnMismatchError,
        /// <summary>
        ///   Looks up a localized string similar to Duplicate language in header..
        /// </summary>
        ImportDuplicateLanguageError,
        /// <summary>
        ///   Looks up a localized string similar to Import failed. Nothing has been imported!.
        /// </summary>
        ImportFailedError,
        /// <summary>
        ///   Looks up a localized string similar to Import failed partially. Some columns have been al....
        /// </summary>
        ImportFailedPartiallyError,
        /// <summary>
        ///   Looks up a localized string similar to Standard header expected..
        /// </summary>
        ImportHeaderMismatchError,
        /// <summary>
        ///   Looks up a localized string similar to The language "{0}" can't be edited. The operation ....
        /// </summary>
        ImportLanguageNotEditable,
        /// <summary>
        ///   Looks up a localized string similar to The sheet "{0}" can't be imported; there is no mat....
        /// </summary>
        ImportMapSheetError,
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid RESX resource file: No xml root....
        /// </summary>
        InvalidResourceFileError,
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid RESX resource file: Not all ent....
        /// </summary>
        InvalidResourceFileNameAttributeMissingError,
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid RESX resource file: Not all ent....
        /// </summary>
        InvalidResourceFileValueAttributeMissingError,
        /// <summary>
        ///   Looks up a localized string similar to This key already exists: {0}.
        /// </summary>
        KeyAlreadyExists,
        /// <summary>
        ///   Looks up a localized string similar to Language is not defined: "{0}".
        /// </summary>
        LanguageNotDefinedError,
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        Neutral,
        /// <summary>
        ///   Looks up a localized string similar to Not all resource files are editable.
        /// </summary>
        NotAllLanguagesAreEditable,
        /// <summary>
        ///   Looks up a localized string similar to Item is invariant but contains a value.
        /// </summary>
        ResourceTableEntry_Error_InvariantWithValue,
        /// <summary>
        ///   Looks up a localized string similar to Missing translation.
        /// </summary>
        ResourceTableEntry_Error_MissingTranslation,
        /// <summary>
        ///   Looks up a localized string similar to Warning: This item contains string format paramete....
        /// </summary>
        ResourceTableEntry_Error_StringFormatParameterMismatch,
        /// <summary>
        ///   Looks up a localized string similar to This rule verifies that the punctuation of the ent....
        /// </summary>
        ResourceTableEntryRulePunctuationLead_Description,
        /// <summary>
        ///   Looks up a localized string similar to The punctuation at the start of the messages doesn....
        /// </summary>
        ResourceTableEntryRulePunctuationLead_Error_Intro,
        /// <summary>
        ///   Looks up a localized string similar to No punctuation was expected at the start of the me....
        /// </summary>
        ResourceTableEntryRulePunctuationLead_Error_NoPunctuationExpected,
        /// <summary>
        ///   Looks up a localized string similar to The expected leading punctuation sequence is: {0}.
        /// </summary>
        ResourceTableEntryRulePunctuationLead_Error_PunctuationSeqExpected,
        /// <summary>
        ///   Looks up a localized string similar to Leading punctuation.
        /// </summary>
        ResourceTableEntryRulePunctuationLead_Name,
        /// <summary>
        ///   Looks up a localized string similar to This rule verifies the punctuation at the end of t....
        /// </summary>
        ResourceTableEntryRulePunctuationTail_Description,
        /// <summary>
        ///   Looks up a localized string similar to The punctuation at the end of the messages doesn't....
        /// </summary>
        ResourceTableEntryRulePunctuationTail_Error_Intro,
        /// <summary>
        ///   Looks up a localized string similar to No punctuation was expected at the end of the mess....
        /// </summary>
        ResourceTableEntryRulePunctuationTail_Error_NoPunctuationExpected,
        /// <summary>
        ///   Looks up a localized string similar to The expected trailing punctuation sequence is: {0}.
        /// </summary>
        ResourceTableEntryRulePunctuationTail_Error_PunctuationSeqExpected,
        /// <summary>
        ///   Looks up a localized string similar to Trailing punctuation.
        /// </summary>
        ResourceTableEntryRulePunctuationTail_Name,
        /// <summary>
        ///   Looks up a localized string similar to This rule verifies that the string format paramete....
        /// </summary>
        ResourceTableEntryRuleStringFormat_Description,
        /// <summary>
        ///   Looks up a localized string similar to Matching string format parameters.
        /// </summary>
        ResourceTableEntryRuleStringFormat_Name,
        /// <summary>
        ///   Looks up a localized string similar to This rule verifies that the whitespaces at the sta....
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceLead_Description,
        /// <summary>
        ///   Looks up a localized string similar to The whitespaces at the start of the sequence don't....
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceLead_Error_Intro,
        /// <summary>
        ///   Looks up a localized string similar to No whitespaces are expected at the start of the se....
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceLead_Error_NoWhiteSpaceExpected,
        /// <summary>
        ///   Looks up a localized string similar to The expected whitespace sequence is: {0}.
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceLead_Error_WhiteSpaceSeqExpected,
        /// <summary>
        ///   Looks up a localized string similar to Leading whitespace.
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceLead_Name,
        /// <summary>
        ///   Looks up a localized string similar to This rule verifies that the trailing whitespaces o....
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceTail_Description,
        /// <summary>
        ///   Looks up a localized string similar to The whitespaces at the end of the sequence don't m....
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceTail_Error_Intro,
        /// <summary>
        ///   Looks up a localized string similar to No whitespaces are expected at the end of the sequ....
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceTail_Error_NoWhiteSpaceExpected,
        /// <summary>
        ///   Looks up a localized string similar to The expected whitespace sequence is: {0}.
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceTail_Error_WhiteSpaceSeqExpected,
        /// <summary>
        ///   Looks up a localized string similar to Trailing whitespace.
        /// </summary>
        ResourceTableEntryRuleWhiteSpaceTail_Name,
        /// <summary>
        ///   Looks up a localized string similar to Snapshot: "{0}".
        /// </summary>
        SnapshotAnnotation,
        /// <summary>
        ///   Looks up a localized string similar to ResX Resource Manager.
        /// </summary>
        /// <remarks>
        /// @Invariant
        /// </remarks>
        Title,
    }

    /// <summary>
    /// Specifies a localized description for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple=false)]
    public sealed class LocalizedDescriptionAttribute : System.ComponentModel.DescriptionAttribute
    {
        private readonly string _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedDescriptionAttribute"/> class.
        /// </summary>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedDescriptionAttribute(StringResourceKey resourceKey)
        {
            _resourceKey = resourceKey.ToString();
        }

        /// <summary>
        /// Gets the localized description from the resource id stored in this attribute.
        /// </summary>
        public override string Description
        {
            get
            {
                return Resources.ResourceManager.GetString(_resourceKey);
            }
        }
    }

    /// <summary>
    /// Specifies a localized display name for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple=false)]
    public sealed class LocalizedDisplayNameAttribute : System.ComponentModel.DisplayNameAttribute
    {
        private readonly string _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedDisplayNameAttribute"/> class.
        /// </summary>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedDisplayNameAttribute(StringResourceKey resourceKey)
        {
            _resourceKey = resourceKey.ToString();
        }

        /// <summary>
        /// Gets the localized display name from the resource id stored in this attribute.
        /// </summary>
        public override string DisplayName
        {
            get
            {
                return Resources.ResourceManager.GetString(_resourceKey);
            }
        }
    }

    /// <summary>
    /// Specifies a localized category for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple=false)]
    public sealed class LocalizedCategoryAttribute : System.ComponentModel.CategoryAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedCategoryAttribute"/> class.
        /// </summary>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedCategoryAttribute(StringResourceKey resourceKey)
            : base(resourceKey.ToString())
        {
        }

        /// <summary>
        /// Gets the localized category name from the resource id stored in this attribute.
        /// </summary>
        protected override string GetLocalizedString(string value)
        {
            return Resources.ResourceManager.GetString(value);
        }
    }

    /// <summary>
    /// Specifies a localized display name for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
    public sealed class LocalizedTextAttribute : global::TomsToolbox.Essentials.TextAttribute
    {
        // This code is generated by Resources.Designer.t4
        // If you get compile errors because you don't use the TomsToolbox.Desktop NuGet package, remove this part in the Resources.Designer.t4 file. 
        // Just search for this text and follow the instructions above.

        private readonly string _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedTextAttribute"/> class.
        /// </summary>
        /// <param name="key">Any user defined key to specify the usage of this text.</param>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedTextAttribute(object key, StringResourceKey resourceKey)
            : base(key)
        {
            _resourceKey = resourceKey.ToString();
        }

        /// <summary>
        /// Gets the localized text from the resource id stored in this attribute.
        /// </summary>
        public override string Text
        {
            get
            {
                return Resources.ResourceManager.GetString(_resourceKey);
            }
        }
    }

    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.DataTypeAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class DataTypeAttribute : System.ComponentModel.DataAnnotations.DataTypeAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="DataTypeAttribute"/> class.
        /// </summary>
        public DataTypeAttribute(StringResourceKey resourceKey, System.ComponentModel.DataAnnotations.DataType dataType)
            : base(dataType)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DataTypeAttribute"/> class.
        /// </summary>
        public DataTypeAttribute(StringResourceKey resourceKey, string customDataType)
            : base(customDataType)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(Resources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    
    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.RangeAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class RangeAttribute : System.ComponentModel.DataAnnotations.RangeAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="RangeAttribute"/> class.
        /// </summary>
        public RangeAttribute(StringResourceKey resourceKey, int minimum, int maximum)
            : base(minimum, maximum)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RangeAttribute"/> class.
        /// </summary>
        public RangeAttribute(StringResourceKey resourceKey, double minimum, double maximum)
            : base(minimum, maximum)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RangeAttribute"/> class.
        /// </summary>
        public RangeAttribute(StringResourceKey resourceKey, Type type, string minimum, string maximum)
            : base(type, minimum, maximum)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(Resources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    
    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.RegularExpressionAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class RegularExpressionAttribute : System.ComponentModel.DataAnnotations.RegularExpressionAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="RegularExpressionAttribute"/> class.
        /// </summary>
        public RegularExpressionAttribute(StringResourceKey resourceKey, string pattern)
            : base(pattern)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(Resources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    
    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.RequiredAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class RequiredAttribute : System.ComponentModel.DataAnnotations.RequiredAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="RequiredAttribute"/> class.
        /// </summary>
        public RequiredAttribute(StringResourceKey resourceKey)
            : base()
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(Resources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    
    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.StringLengthAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class StringLengthAttribute : System.ComponentModel.DataAnnotations.StringLengthAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="StringLengthAttribute"/> class.
        /// </summary>
        public StringLengthAttribute(StringResourceKey resourceKey, int maximumLength)
            : base(maximumLength)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(Resources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    

}
