@ECHO OFF

FOR /R %%a in (*.*proj) DO CALL :CLEAN "%%~dpa"
GOTO :EOF

:CLEAN
CALL :REMOVEDIR "%~1obj"
CALL :REMOVEDIR "%~1bin"
CALL :DELETEFILE "%~1*_wpftmp.csproj"
GOTO :EOF

:REMOVEDIR
IF NOT EXIST %1 GOTO :EOF
@ECHO REMOVE %1
RD /s /q %1
:EOF

:DELETEFILE
IF NOT EXIST %1 GOTO :EOF
@ECHO DELETE %1
DEL %1
:EOF