//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tomenglertde.ResXManager.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tomenglertde.ResXManager.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new key (Shift+Insert).
        /// </summary>
        public static string AddKeyToolTip {
            get {
                return ResourceManager.GetString("AddKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new language.
        /// </summary>
        public static string AddLanguageToolTip {
            get {
                return ResourceManager.GetString("AddLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sens..
        /// </summary>
        public static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose columns.
        /// </summary>
        public static string ChooseColumnsToolTip {
            get {
                return ResourceManager.GetString("ChooseColumnsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of references found in code files. This is only a hint for possible usages, see documentation for more details!.
        /// </summary>
        public static string CodeReferencesToolTip {
            get {
                return ResourceManager.GetString("CodeReferencesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentColumnHeader {
            get {
                return ResourceManager.GetString("CommentColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Token.
        /// </summary>
        public static string CommentToken {
            get {
                return ResourceManager.GetString("CommentToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Configuration_General {
            get {
                return ResourceManager.GetString("Configuration_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load &amp; Save.
        /// </summary>
        public static string Configuration_LoadSaveHeader {
            get {
                return ResourceManager.GetString("Configuration_LoadSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string ConfigurationScopeHeader {
            get {
                return ResourceManager.GetString("ConfigurationScopeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut the selected rows?.
        /// </summary>
        public static string ConfirmCutItems {
            get {
                return ResourceManager.GetString("ConfirmCutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected rows?.
        /// </summary>
        public static string ConfirmDeleteItems {
            get {
                return ResourceManager.GetString("ConfirmDeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy key(s).
        /// </summary>
        public static string CopyKeys {
            get {
                return ResourceManager.GetString("CopyKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected rows (Ctrl+C).
        /// </summary>
        public static string CopyToolTip {
            get {
                return ResourceManager.GetString("CopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selected rows (Ctrl+X).
        /// </summary>
        public static string CutToolTip {
            get {
                return ResourceManager.GetString("CutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (Del).
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected rows (Del).
        /// </summary>
        public static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude files:.
        /// </summary>
        public static string DetectCodeReferences_Exclude {
            get {
                return ResourceManager.GetString("DetectCodeReferences_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Code References.
        /// </summary>
        public static string DetectCodeReferences_Header {
            get {
                return ResourceManager.GetString("DetectCodeReferences_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan files:.
        /// </summary>
        public static string DetectCodeReferences_Scan {
            get {
                return ResourceManager.GetString("DetectCodeReferences_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the Open Source Community..
        /// </summary>
        public static string DonateButtonToolTip {
            get {
                return ResourceManager.GetString("DonateButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are editing the default configuration. If you want to change settings that apply only to a specific solution, just open the solution..
        /// </summary>
        public static string EditDefaultConfigurationNotification {
            get {
                return ResourceManager.GetString("EditDefaultConfigurationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are editing the configuration specific for the active solution. If you want to edit the default configuration, just close the solution..
        /// </summary>
        public static string EditSolutionConfigurationNotification {
            get {
                return ResourceManager.GetString("EditSolutionConfigurationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmptyResxTemplate {
            get {
                return ResourceManager.GetString("EmptyResxTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding the new resource file &apos;{0}&apos;..
        /// </summary>
        public static string ErrorAddingNewResourceFile {
            get {
                return ResourceManager.GetString("ErrorAddingNewResourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all.
        /// </summary>
        public static string ExportExcelAll {
            get {
                return ResourceManager.GetString("ExportExcelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selection.
        /// </summary>
        public static string ExportExcelSelection {
            get {
                return ResourceManager.GetString("ExportExcelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists. Do you want to overwrite it?.
        /// </summary>
        public static string FileExistsPrompt {
            get {
                return ResourceManager.GetString("FileExistsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extensions.
        /// </summary>
        public static string FileExtensions {
            get {
                return ResourceManager.GetString("FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect code references..
        /// </summary>
        public static string FindCodeReferencesButtonToolTip {
            get {
                return ResourceManager.GetString("FindCodeReferencesButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat view.
        /// </summary>
        public static string FlatViewToolTip {
            get {
                return ResourceManager.GetString("FlatViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped view.
        /// </summary>
        public static string GroupedViewToolTip {
            get {
                return ResourceManager.GetString("GroupedViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string HelpButtonToolTip {
            get {
                return ResourceManager.GetString("HelpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportExcel {
            get {
                return ResourceManager.GetString("ImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant.
        /// </summary>
        public static string Invariant {
            get {
                return ResourceManager.GetString("Invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an overview of the languages supported by the system. It shows the specific languages (e.g. &apos;en-US&apos;) grouped by their neutral language (e.g. &apos;en&apos;). To change the flag displayed for a neutral language, double click the specific language with the desired flag..
        /// </summary>
        public static string LanguageConfiguration_Description {
            get {
                return ResourceManager.GetString("LanguageConfiguration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like it? Support the project by writing a short review!.
        /// </summary>
        public static string LikeButtonToolTip {
            get {
                return ResourceManager.GetString("LikeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple selection..
        /// </summary>
        public static string MultipleSelection {
            get {
                return ResourceManager.GetString("MultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to change the neutral language icon..
        /// </summary>
        public static string NeutralLanguageToolTip {
            get {
                return ResourceManager.GetString("NeutralLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral Resources Language:.
        /// </summary>
        public static string NeutralResourceLanguageHeader {
            get {
                return ResourceManager.GetString("NeutralResourceLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new resource key:.
        /// </summary>
        public static string NewKeyPrompt {
            get {
                return ResourceManager.GetString("NewKeyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new language id:.
        /// </summary>
        public static string NewLanguageIdPrompt {
            get {
                return ResourceManager.GetString("NewLanguageIdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code references have been found by this algorithm. Nevertheless there might exist indirect references to this string..
        /// </summary>
        public static string NoCodeReferencesToolTip {
            get {
                return ResourceManager.GetString("NoCodeReferencesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selection..
        /// </summary>
        public static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste rows (Ctrl+V).
        /// </summary>
        public static string PasteToolTip {
            get {
                return ResourceManager.GetString("PasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh view.
        /// </summary>
        public static string RefreshViewToolTip {
            get {
                return ResourceManager.GetString("RefreshViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A regular expression to filter resource files.
        /// </summary>
        public static string ResourceFilterToolTip {
            get {
                return ResourceManager.GetString("ResourceFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected/Total.
        /// </summary>
        public static string SelectedTotalToolTip {
            get {
                return ResourceManager.GetString("SelectedTotalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string ShellTabHeader_Languages {
            get {
                return ResourceManager.GetString("ShellTabHeader_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellTabHeader_Main {
            get {
                return ResourceManager.GetString("ShellTabHeader_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only lines with missing strings.
        /// </summary>
        public static string ShowOnlyMissingToolTip {
            get {
                return ResourceManager.GetString("ShowOnlyMissingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort all files now.
        /// </summary>
        public static string SortAllFilesNow {
            get {
                return ResourceManager.GetString("SortAllFilesNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When saving a RESX file, sort the XML data nodes by the key..
        /// </summary>
        public static string SortNodesByKey {
            get {
                return ResourceManager.GetString("SortNodesByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to sort all nodes of all resource files by the key now?.
        /// </summary>
        public static string SortNodesByKey_Confirmation {
            get {
                return ResourceManager.GetString("SortNodesByKey_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResX Resource Manager.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
