//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tomenglertde.ResXManager.View.Properties {
    using System;
    using System.Diagnostics.Contracts;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by a text template.
    // To add or remove a member, edit your .ResX file.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tomenglertde.ResXManager.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add new key (Shift+Insert).
        /// </summary>
        public static string AddKeyToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("AddKeyToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add new language.
        /// </summary>
        public static string AddLanguageToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("AddLanguageToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Authentication", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create all resource files when adding a new resour....
        /// </summary>
        public static string AutoCreateNewLanguageFiles {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("AutoCreateNewLanguageFiles", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Case Sens..
        /// </summary>
        /// <remarks>
        /// @Invariant
        /// </remarks>
        public static string CaseSensitive {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("CaseSensitive", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose columns.
        /// </summary>
        public static string ChooseColumnsToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ChooseColumnsToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The number of references found in code files. This....
        /// </summary>
        public static string CodeReferencesToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("CodeReferencesToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code reference detection is still in progress ({0}....
        /// </summary>
        public static string CodeReferenceTrackingInProgress {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("CodeReferenceTrackingInProgress", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Comment", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentColumnHeader {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("CommentColumnHeader", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment Token.
        /// </summary>
        public static string CommentToken {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("CommentToken", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excel export mode.
        /// </summary>
        public static string Configuration_ExcelExportModeHeader {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Configuration_ExcelExportModeHeader", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File creation.
        /// </summary>
        public static string Configuration_FileCreationHeader {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Configuration_FileCreationHeader", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Configuration_General {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Configuration_General", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load &amp; Save.
        /// </summary>
        public static string Configuration_LoadSaveHeader {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Configuration_LoadSaveHeader", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string ConfigurationScopeHeader {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ConfigurationScopeHeader", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm adding new resource files.
        /// </summary>
        public static string ConfirmAddLanguage {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ConfirmAddLanguage", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut the selected rows?.
        /// </summary>
        public static string ConfirmCutItems {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ConfirmCutItems", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete the selected rows?.
        /// </summary>
        public static string ConfirmDeleteItems {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ConfirmDeleteItems", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        public static string Copy {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Copy", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy key(s).
        /// </summary>
        public static string CopyKeys {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("CopyKeys", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy selected rows (Ctrl+C).
        /// </summary>
        public static string CopyToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("CopyToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        public static string Cut {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Cut", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut selected rows (Ctrl+X).
        /// </summary>
        public static string CutToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("CutToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete (Del).
        /// </summary>
        public static string Delete {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Delete", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete selected rows (Del).
        /// </summary>
        public static string DeleteToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("DeleteToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detect Code References.
        /// </summary>
        public static string DetectCodeReferences_Header {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("DetectCodeReferences_Header", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Support the Open Source Community..
        /// </summary>
        public static string DonateButtonToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("DonateButtonToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your are editing the default configuration. If you....
        /// </summary>
        public static string EditDefaultConfigurationNotification {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("EditDefaultConfigurationNotification", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are editing the configuration specific for the....
        /// </summary>
        public static string EditSolutionConfigurationNotification {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("EditSolutionConfigurationNotification", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;?xml version="1.0" encoding="utf-8"?&amp;g....
        /// </summary>
        public static string EmptyResxTemplate {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("EmptyResxTemplate", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Enabled", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error adding the new resource file '{0}'..
        /// </summary>
        public static string ErrorAddingNewResourceFile {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ErrorAddingNewResourceFile", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export all.
        /// </summary>
        public static string ExportExcelAll {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ExportExcelAll", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export selection.
        /// </summary>
        public static string ExportExcelSelection {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ExportExcelSelection", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Extensions.
        /// </summary>
        public static string FileExtensions {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("FileExtensions", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detect code references..
        /// </summary>
        public static string FindCodeReferencesButtonToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("FindCodeReferencesButtonToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Flat view.
        /// </summary>
        public static string FlatViewToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("FlatViewToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grouped view.
        /// </summary>
        public static string GroupedViewToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("GroupedViewToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string HelpButtonToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("HelpButtonToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportExcel {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ImportExcel", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invariant.
        /// </summary>
        public static string Invariant {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Invariant", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Key", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is an overview of the languages supported by ....
        /// </summary>
        public static string LanguageConfiguration_Description {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("LanguageConfiguration_Description", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Like it? Support the project by writing a short re....
        /// </summary>
        public static string LikeButtonToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("LikeButtonToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple selection..
        /// </summary>
        public static string MultipleSelection {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("MultipleSelection", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string Neutral {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Neutral", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Neutral Resources Language:.
        /// </summary>
        public static string NeutralResourceLanguageHeader {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("NeutralResourceLanguageHeader", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter new resource key:.
        /// </summary>
        public static string NewKeyPrompt {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("NewKeyPrompt", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the new language:.
        /// </summary>
        public static string NewLanguageIdPrompt {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("NewLanguageIdPrompt", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No code references have been found by this algorit....
        /// </summary>
        public static string NoCodeReferencesToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("NoCodeReferencesToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no resource file for this resource..
        /// </summary>
        public static string NoResourceFileForResource {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("NoResourceFileForResource", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No selection..
        /// </summary>
        public static string NoSelection {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("NoSelection", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        public static string Paste {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Paste", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste rows (Ctrl+V).
        /// </summary>
        public static string PasteToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("PasteToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh view.
        /// </summary>
        public static string RefreshViewToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("RefreshViewToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string RegularExpression {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("RegularExpression", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A regular expression to filter resource files.
        /// </summary>
        public static string ResourceFilterToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ResourceFilterToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected/Total.
        /// </summary>
        public static string SelectedTotalToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("SelectedTotalToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ShellTabHeader_Configuration {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ShellTabHeader_Configuration", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string ShellTabHeader_Languages {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ShellTabHeader_Languages", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellTabHeader_Main {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ShellTabHeader_Main", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string ShellTabHeader_Translate {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ShellTabHeader_Translate", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show only lines with missing strings.
        /// </summary>
        public static string ShowOnlyMissingToolTip {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("ShowOnlyMissingToolTip", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort all files now.
        /// </summary>
        public static string SortAllFilesNow {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("SortAllFilesNow", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort using:.
        /// </summary>
        public static string SortBy {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("SortBy", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When saving a RESX file, sort the XML data nodes b....
        /// </summary>
        public static string SortNodesByKey {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("SortNodesByKey", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to sort all nodes of all resource file....
        /// </summary>
        public static string SortNodesByKey_Confirmation {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("SortNodesByKey_Confirmation", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ResX Resource Manager.
        /// </summary>
        /// <remarks>
        /// @Invariant
        /// </remarks>
        public static string Title {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Title", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply All.
        /// </summary>
        public static string Translations_ApplyAll {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Translations_ApplyAll", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply Selected.
        /// </summary>
        public static string Translations_ApplySelected {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Translations_ApplySelected", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Translations_Restart {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Translations_Restart", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string Translations_Source {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Translations_Source", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Translations_Stop {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Translations_Stop", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Targets:.
        /// </summary>
        public static string Translations_Targets {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("Translations_Targets", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Prefix translations with .
        /// </summary>
        public static string TranslationsPrefixHeader {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("TranslationsPrefixHeader", resourceCulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save credentials (Credentials will be stored as cl....
        /// </summary>
        public static string TranslatorConfiguration_SaveCredentials {
            get {
                Contract.Ensures(Contract.Result<string>() != null);
                return ResourceManager.GetString("TranslatorConfiguration_SaveCredentials", resourceCulture) ?? string.Empty;
            }
        }
    }

    /// <summary>
    /// Keys of all available strings in the applications resx-resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public enum StringResourceKey
    {
        /// <summary>
        ///   Looks up a localized string similar to Add new key (Shift+Insert).
        /// </summary>
        AddKeyToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Add new language.
        /// </summary>
        AddLanguageToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        Authentication,
        /// <summary>
        ///   Looks up a localized string similar to Create all resource files when adding a new resour....
        /// </summary>
        AutoCreateNewLanguageFiles,
        /// <summary>
        ///   Looks up a localized string similar to Case Sens..
        /// </summary>
        /// <remarks>
        /// @Invariant
        /// </remarks>
        CaseSensitive,
        /// <summary>
        ///   Looks up a localized string similar to Choose columns.
        /// </summary>
        ChooseColumnsToolTip,
        /// <summary>
        ///   Looks up a localized string similar to The number of references found in code files. This....
        /// </summary>
        CodeReferencesToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Code reference detection is still in progress ({0}....
        /// </summary>
        CodeReferenceTrackingInProgress,
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        Comment,
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        CommentColumnHeader,
        /// <summary>
        ///   Looks up a localized string similar to Comment Token.
        /// </summary>
        CommentToken,
        /// <summary>
        ///   Looks up a localized string similar to Excel export mode.
        /// </summary>
        Configuration_ExcelExportModeHeader,
        /// <summary>
        ///   Looks up a localized string similar to File creation.
        /// </summary>
        Configuration_FileCreationHeader,
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        Configuration_General,
        /// <summary>
        ///   Looks up a localized string similar to Load &amp; Save.
        /// </summary>
        Configuration_LoadSaveHeader,
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        ConfigurationScopeHeader,
        /// <summary>
        ///   Looks up a localized string similar to Confirm adding new resource files.
        /// </summary>
        ConfirmAddLanguage,
        /// <summary>
        ///   Looks up a localized string similar to Cut the selected rows?.
        /// </summary>
        ConfirmCutItems,
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected rows?.
        /// </summary>
        ConfirmDeleteItems,
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        Copy,
        /// <summary>
        ///   Looks up a localized string similar to Copy key(s).
        /// </summary>
        CopyKeys,
        /// <summary>
        ///   Looks up a localized string similar to Copy selected rows (Ctrl+C).
        /// </summary>
        CopyToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        Cut,
        /// <summary>
        ///   Looks up a localized string similar to Cut selected rows (Ctrl+X).
        /// </summary>
        CutToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Delete (Del).
        /// </summary>
        Delete,
        /// <summary>
        ///   Looks up a localized string similar to Delete selected rows (Del).
        /// </summary>
        DeleteToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Detect Code References.
        /// </summary>
        DetectCodeReferences_Header,
        /// <summary>
        ///   Looks up a localized string similar to Support the Open Source Community..
        /// </summary>
        DonateButtonToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Your are editing the default configuration. If you....
        /// </summary>
        EditDefaultConfigurationNotification,
        /// <summary>
        ///   Looks up a localized string similar to You are editing the configuration specific for the....
        /// </summary>
        EditSolutionConfigurationNotification,
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;?xml version="1.0" encoding="utf-8"?&amp;g....
        /// </summary>
        EmptyResxTemplate,
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        Enabled,
        /// <summary>
        ///   Looks up a localized string similar to Error adding the new resource file '{0}'..
        /// </summary>
        ErrorAddingNewResourceFile,
        /// <summary>
        ///   Looks up a localized string similar to Export all.
        /// </summary>
        ExportExcelAll,
        /// <summary>
        ///   Looks up a localized string similar to Export selection.
        /// </summary>
        ExportExcelSelection,
        /// <summary>
        ///   Looks up a localized string similar to File Extensions.
        /// </summary>
        FileExtensions,
        /// <summary>
        ///   Looks up a localized string similar to Detect code references..
        /// </summary>
        FindCodeReferencesButtonToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Flat view.
        /// </summary>
        FlatViewToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Grouped view.
        /// </summary>
        GroupedViewToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        HelpButtonToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        ImportExcel,
        /// <summary>
        ///   Looks up a localized string similar to Invariant.
        /// </summary>
        Invariant,
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        Key,
        /// <summary>
        ///   Looks up a localized string similar to This is an overview of the languages supported by ....
        /// </summary>
        LanguageConfiguration_Description,
        /// <summary>
        ///   Looks up a localized string similar to Like it? Support the project by writing a short re....
        /// </summary>
        LikeButtonToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Multiple selection..
        /// </summary>
        MultipleSelection,
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        Neutral,
        /// <summary>
        ///   Looks up a localized string similar to Neutral Resources Language:.
        /// </summary>
        NeutralResourceLanguageHeader,
        /// <summary>
        ///   Looks up a localized string similar to Enter new resource key:.
        /// </summary>
        NewKeyPrompt,
        /// <summary>
        ///   Looks up a localized string similar to Select the new language:.
        /// </summary>
        NewLanguageIdPrompt,
        /// <summary>
        ///   Looks up a localized string similar to No code references have been found by this algorit....
        /// </summary>
        NoCodeReferencesToolTip,
        /// <summary>
        ///   Looks up a localized string similar to There is no resource file for this resource..
        /// </summary>
        NoResourceFileForResource,
        /// <summary>
        ///   Looks up a localized string similar to No selection..
        /// </summary>
        NoSelection,
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        Paste,
        /// <summary>
        ///   Looks up a localized string similar to Paste rows (Ctrl+V).
        /// </summary>
        PasteToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Refresh view.
        /// </summary>
        RefreshViewToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        RegularExpression,
        /// <summary>
        ///   Looks up a localized string similar to A regular expression to filter resource files.
        /// </summary>
        ResourceFilterToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Selected/Total.
        /// </summary>
        SelectedTotalToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        ShellTabHeader_Configuration,
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        ShellTabHeader_Languages,
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        ShellTabHeader_Main,
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        ShellTabHeader_Translate,
        /// <summary>
        ///   Looks up a localized string similar to Show only lines with missing strings.
        /// </summary>
        ShowOnlyMissingToolTip,
        /// <summary>
        ///   Looks up a localized string similar to Sort all files now.
        /// </summary>
        SortAllFilesNow,
        /// <summary>
        ///   Looks up a localized string similar to Sort using:.
        /// </summary>
        SortBy,
        /// <summary>
        ///   Looks up a localized string similar to When saving a RESX file, sort the XML data nodes b....
        /// </summary>
        SortNodesByKey,
        /// <summary>
        ///   Looks up a localized string similar to Do you want to sort all nodes of all resource file....
        /// </summary>
        SortNodesByKey_Confirmation,
        /// <summary>
        ///   Looks up a localized string similar to ResX Resource Manager.
        /// </summary>
        /// <remarks>
        /// @Invariant
        /// </remarks>
        Title,
        /// <summary>
        ///   Looks up a localized string similar to Apply All.
        /// </summary>
        Translations_ApplyAll,
        /// <summary>
        ///   Looks up a localized string similar to Apply Selected.
        /// </summary>
        Translations_ApplySelected,
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        Translations_Restart,
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        Translations_Source,
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        Translations_Stop,
        /// <summary>
        ///   Looks up a localized string similar to Targets:.
        /// </summary>
        Translations_Targets,
        /// <summary>
        ///   Looks up a localized string similar to Prefix translations with .
        /// </summary>
        TranslationsPrefixHeader,
        /// <summary>
        ///   Looks up a localized string similar to Save credentials (Credentials will be stored as cl....
        /// </summary>
        TranslatorConfiguration_SaveCredentials,
    }

    /// <summary>
    /// Specifies a localized description for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple=false)]
    public sealed class LocalizedDescriptionAttribute : System.ComponentModel.DescriptionAttribute
    {
        private readonly StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedDescriptionAttribute"/> class.
        /// </summary>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedDescriptionAttribute(StringResourceKey resourceKey)
        {
            _resourceKey = resourceKey;
        }

        /// <summary>
        /// Gets the localized description from the resource id stored in this attribute.
        /// </summary>
        public override string Description
        {
            get
            {
                return Resources.ResourceManager.GetString(_resourceKey.ToString());
            }
        }
    }

    /// <summary>
    /// Specifies a localized display name for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple=false)]
    public sealed class LocalizedDisplayNameAttribute : System.ComponentModel.DisplayNameAttribute
    {
        private readonly StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedDisplayNameAttribute"/> class.
        /// </summary>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedDisplayNameAttribute(StringResourceKey resourceKey)
        {
            _resourceKey = resourceKey;
        }

        /// <summary>
        /// Gets the localized display name from the resource id stored in this attribute.
        /// </summary>
        public override string DisplayName
        {
            get
            {
                return Resources.ResourceManager.GetString(_resourceKey.ToString());
            }
        }
    }


    /// <summary>
    /// Specifies a localized display name for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
    public sealed class LocalizedTextAttribute : global::TomsToolbox.Desktop.TextAttribute
    {
        private readonly StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedTextAttribute"/> class.
        /// </summary>
        /// <param name="key">Any user defined key to specify the usage of this text.</param>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedTextAttribute(object key, StringResourceKey resourceKey)
            : base(key)
        {
            _resourceKey = resourceKey;
        }

        /// <summary>
        /// Gets the localized text from the resource id stored in this attribute.
        /// </summary>
        public override string Text
        {
            get
            {
                return Resources.ResourceManager.GetString(_resourceKey.ToString());
            }
        }
    }



}

